version: "3.4"

services:
  propeiredb:
    container_name: propeiredb
    build:
      context: ./
      dockerfile: Dockerfile
    #entrypoint: cd src && gunicorn wsgi:server -b 8000
    entrypoint: sleep infinity
    restart: unless-stopped
    environment:
      POSTGRES_DSN: postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-password}@propeiredb-pgdb:5432/${POSTGRES_DB:-property_register}
      REDIS_DSN: ${REDIS_DSN:-redis://propeiredb-redis:6379}
      GOOGLE_MAPS_KEY: ${GOOGLE_MAPS_KEY:-}
    volumes:
      - ./:/workspace
    ports:
      - "8000:8000"

  #sudo docker exec -it pgdb_property psql -U property -d property_register
  postgres:
    container_name: propeiredb-pgdb
    image: postgres:14.2-alpine
    restart: unless-stopped
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    shm_size: '512mb'  # Adjust based on your needs
    command:
      -c 'max_connections=200'
      -c 'shared_buffers=256MB'

    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
    expose:
      - 5432

  propeiredb_redis:
    container_name: propeiredb-redis
    image: redis:5.0.6-alpine
    restart: unless-stopped
    command: redis-server
    expose:
      - 6379
